### PR TITLE
Parallelism Implementation

### PR DESCRIPTION
**Pull request by CCKRK**
Alright, this is closer to a real start for parallelism -- some things that need to be checked out:

I am currently accomplishing simultaneous trades by first creating a vector<Result> entryVec with all possible trade combinations, then fetching previously opened trades from the database and pushing them into a vector<Result> tradeVec, and then removing those exchanges pairings in tradeVec from the entryVec. This is accomplished in sort of a hacky manner (see end of Result.cpp) but it doesn't really need to be super efficient since it is only run once. I think sets would be better (since these vectors really are ordered.. ) but this is how I've done it. I'm concerned I missed something about the trailing/trailing wait count arrays and something unforseen is not being calculated.

The DB functions which save/restore trades are also pretty clunky (trades_cb..) -- I'm afraid there might be some leak in there so please check it out.

Exchanges will all require a new kind of getActivePos implementation which will take an orderId and return that orders size, you can see how this will be accomplished in:
GDAX
Bittrex
Poloniex
Kraken

I'll do the others once I receive some feedback on the way this is working.

Balances for performance calculations haven't even been touched yet, so that portion fo blackbird is not working in this PR. I also can't test sendEmail but I would assume it is not working. The stop_after_notrade file trick isn't working either but that is a pretty simple fix.

This kind of trading makes a few parameters in the Result struct obsolete, we should remove them before actually adding this.

Let me know what you think, this still requires quite a bit of work before it's ready for production.
ref #404

### CODE REVIEW

**Comment by butor** [comment]
Thanks @CCKRK. That's a big change but it looks OK to me.

**Comment by CCKRK** [comment]
Well, it certainly works (at least with what I'm able to test.. hope I can get at least one more short exchange soon) but I need some help with the balances for calculating performance. They're completely off at the moment and I'm not sure what the logic is. I suppose it's enough to save Exposure from the entry trade as leg2TotBalanceBefore (this can be sent to db for persistence across sessions), but how can we get an accurate representation of our USD value we get back in checkExit?

The Balance vector doesn't do what you intended it to do anymore, but it's important to keep (in my opinion) so we can always be sure we've got balances ready to rock to fire out more orders.

I also can't truly test sendEmail, none of my addresses will allow simple smtp. 

Definitely minor concerns considering our goal is to make money, but you've made a nice project here and I don't want my sloppy code making a mess of it.

**Comment by davidjirovec** [comment]
What is the status of this pull request? Is it waiting only for testing? I can short sell on Bitfinex and Kraken, so I could try it. Could you please synchronise it with master?

**Comment by CCKRK** [comment]
1. The BalanceVector/print statements are not functioning correctly
2. SendEmail functionality is not functioning
3. I have not added members to many of the exchanges to take an orderId in GetActivePos member which could cause undue closure of positions (and thus loss of funds)
4. Controls are not properly in place for the average user (no exit_failure for other currency pairs, does not care if you have BTC in your accounts)
5. _Stop_After_no_trade control is not implemented.
6. there should be more controls on disabling/enabling exchanges with trades left open, or a new exchangeId regime needs to be implemented.

I won't merge until the above issues are fixed in a way that is at least relatable to the current codebase. I can confirm that it works properly on:

- Poloniex
- Binance
- Bittrex
- Kraken
- GDAX

So if you trade those markets give it a whirl.

**Comment by CCKRK** [comment]
@butor do you mind if I make a branch for this for now? It can be merged with master later when we've got some more tests/eyes on it -- I'll update readme on the branch to reflect experimental status/functionality

**Comment by butor** [comment]
> do you mind if I make a branch for this for now? It can be merged with master later when we've got some more tests/eyes on it -- I'll update readme on the branch to reflect experimental status/functionality

No problem @CCKRK

**Comment by CCKRK** [comment]
Closing this PR as it will be added as a branch for now.

**Pull request closed without merging**
