### PR TITLE
Easier debugging/editing

### PR DESCRIPTION
**Pull request by jleonelion**
I created some additional files and scripts to make it easier for people to develop and debug code using GDB and the open source VS Code editor.  Please consider pulling these files (and the instructions I created in the README)

### CODE REVIEW

**Comment by greatwolf** [comment]
I'm not too familiar with it. It looks ok to me at a glance.

**Comment by rubiwane** [comment]
I need someone to install BB on my server. Does someone is interested for some $?

**Comment by ezhangTribalScale** [comment]
Hi thanks for adding the debug support. But I keep getting this error when I hit F5:
Unable to start debugging. Program path '/Users/yuduozhang/workspace/blackbird/blackbird' is missing or invalid.
Any idea how to resolve it?

Thanks,
Ed.

**Comment by jleonelion** [comment]
Ed,

When you hit F5, VS Code should run the "launch debug container" task (defined in tasks.json).  

Are you able to successfully run this command from the terminal (in root directory of your blackbird workspace)?
docker-compose -f docker-compose.yml -f docker-compose.debug.yml up

**Pull request merged**
