### PR TITLE
GDAX Integration starting point

### PR DESCRIPTION
**Pull request by CCKRK**
Hi all,

I'm working on GDAX integration and I've hit a point where I wanted some outside input/edits -- I don't think this PR should be merged until some of the issues are fixed. 

The current PR will build just fine and all of the functions work up to sending the actual order (important...) which is where I may need some help. If I'm reading GDAX API docs correctly what they want hashed when sending an order is a string that looks exactly like a JSON object and to have that JSON object/string posted in the body of our message. I've seen similar things done in the implementation of Bitfinex and the Quadriga exchanges and I'd like some input on which style is preferable. Should we create a JSON object in the sendLongOrder member and decode it into a string in our AuthRequest member, or perhaps forget JSON altogether as in the Bitfinex implementation? Currently, I am consistently getting an invalid signature message when attempting to POST an order.

Thanks in advance.

### CODE REVIEW

**Comment by irufus** [comment]
Is there any reason why you wouldn't look into utilizing their FIX systems if RestAPI + JSON is too much of a problem? I would imagine the overhead via web requests would not be ideal.

**Comment by CCKRK** [comment]
I feel like making a FIX client might be outside of the scope of the project -- I'm mostly trying to make additions that cohere to what BlackBird has already established in terms of style. 

I agree with your comment in regards to overhead. Once I have implemented all the exchanges I personally trade on I may go back over those exchanges to try to implement things like sockets/FIX. Fixing the hardcoding of currencies/an OO refactor is higher on my priority list, though.

**Comment by CCKRK** [comment]
This PR should now be ready for review/merge.

I made a custom time function in GDAX.cpp that may not be necessary (perhaps use time_fun?) and I hope there are no errors in the Readme.

Tested with real money and everything checked out.

**Comment by butor** [comment]
Awesome thanks @CCKRK

**Pull request merged**
