### PR TITLE
Blackbird can remember now.

### PR DESCRIPTION
**Pull request by jackeown**
I think I've made it so that blackbird can remember that it was in the middle of a trade. Hope this works

### CODE REVIEW

**Comment by greatwolf** [comment]
I wonder if it'll make more sense to just store this as a table in sqlite instead.

**Comment by butor** [comment]
@greatwolf yes maybe. I accepted #130 for the moment

**Comment by cihanbilir** [comment]
Is this the default behaviour now even if the process is killed unintentionally?
Or do you have to pass a param in some way during the restart.
(just started testing with three exchanges , haven't checked the code, thanks a bunch for all your effort)

**Comment by jackeown** [comment]
I believe this is default behavior now.  If you wanted Blackbird to forget
it you could just delete the restore.txt file and restart Blackbird

**Pull request merged**
