### PR TITLE
Removed Bitfinex (Post-Security Breach)

### PR DESCRIPTION
**Pull request by nickfogle**
@butor, Do you think it makes sense to remove Bitfinex from Blackbird's list of supported trading platforms? 

They have closed their doors to trading, and it seems highly unlikely they'll return to normal trading operations. Given the nature of the hack and the total financial loss, I don't think they'll be a viable arbitrage opportunity going forward. 

Best of luck to anyone who was carrying a large balance over there!

### CODE REVIEW

**Comment by irufus** [comment]
Their post on August 3rd (on the main site) implies they are trying to make a return.  

Seems a bit silly to remove code that you may have to restore further down the rode.

**Comment by nickfogle** [comment]
@irufus you've got a point, it may be too early to dismiss Bitfinex and scrub them from Blackbird. Hopefully they'll provide a meaningful announcement within the next few days. It would be very impressive if they were somehow able to avoid insolvency here, but I'm just not optimistic. 

I continue to follow this closely and am eager to unwind my account as soon as they re-enable access.

**Comment by alfonsoperez** [comment]
They are back, nope?

**Comment by thejackluo** [comment]
Back but never with the same trust again

**Pull request closed without merging**
