### PR TITLE
SevenNintySixExchangeAdded

### PR DESCRIPTION
**Pull request by venky-bommireddy**
I have implemented to support  796.com exchange,
 please review.

Thanks,

### CODE REVIEW

**Comment by butor** [comment]
Thanks @venky-bommireddy for your pull request.
I didn't test but I merged anyway as your code doesn't modify the core Blackbird engine.
796.com only offers Bitcoin Futures, correct? It will be interesting to see the spreads then.

**Comment by venky-bommireddy** [comment]
Yes,

It offers only bitcoin feature.

**Comment by butor** [comment]
Hi @venky-bommireddy 
Isn't it possible to short sell on 796.com? It looks like they offer short selling, but maybe not through their API though?

**Comment by venky-bommireddy** [comment]
They have provided limited functionality through API.
I think that is under progress (v3) in 796.com

**Comment by venky-bommireddy** [comment]
Have you tested 796.com

**Pull request merged**
