### PR TITLE
Kraken Short Support

### PR DESCRIPTION
**Pull request by raffelino**
According to the api and https://github.com/butor/blackbird/issues/360 Kraken should support Short orders. Right now, I'm not verified with Kraken so I can't test this by myself, maybe someone else wants to?

### CODE REVIEW

**Comment by butor** [comment]
Thanks @raffelino, but I don't see the actual implementation of the short selling function. Both `sendLongOrder()` and `sendShortOrder()` call the exact same `sendOrder()` function with the same arguments. Am I missing something?

**Comment by raffelino** [comment]
Thought that this would suffice as it would be called with 'sell' as direction creating a short if no btc are within the wallet. I'll refine it as soon as I get verified by kraken.com.

**Comment by ArtjomIV** [comment]
Would like to ask how is there going with Kraken implementation? as Bitfinex is not accepting new registrations

**Comment by nspassov** [comment]
Hey @raffelino, is shorting working with Kraken now that their maintenance is over?

**Comment by aleixsb** [comment]
As it's explained in the link below to start a short or long position you should open a sell or buy order, but the type of the order should be Settle Position (API: settle-position ) not limit.

https://support.kraken.com/hc/en-us/articles/218741078-What-is-settling-a-position-and-how-do-I-do-it-


So at least for the shortorder ordertype should be set to settle-position.

I'm not sure for the long one... I don't know which of two options should be implemented to behave as blackbird expects, if you open a long position with an ordertype=limit, the funds will be deducted from you account, but if you also set ordertype=settle-position then you will start a long position and the won't be deducted untill the order is closed. 

@butor  can you provide support with this? Is the long order meant to deduct from the acc balance or should it open a long position as in the short order?

**Comment by butor** [comment]
Thanks @aleixsb 

I think that the long position will be a standard limit order and the short position will be indeed a `settle-position`. We can also ask [Kraken Support](https://support.kraken.com/hc/en-us/requests/new) for clarification.

I don't think we need `settle-position` with the long order, unless we are using leverage. That can be something to keep in mind if we can implement leverage on other exchanges.

**Comment by nspassov** [comment]
I want to help with this implementation, but my finance skills are still pretty basic. Are there any additional methods that need implementing here or it's just a matter of figuring out the correct order type for the long order?

**Comment by JinjaNinja22** [comment]
Does this mean the code for Kraken shorting has now been merged in?

**Comment by swiftaction** [comment]
I'm verified on Kraken @raffelino Have you had a chance to test this yet?

**Comment by swiftaction** [comment]
@butor @raffelino I believe to short you need you use a sell order _with leverage_ you then create and opposing buy  order with leverage to close the trade out. Or I believe the settle-position will work too.

https://www.youtube.com/watch?v=BeKbltL3kCw

**Comment by dixia** [comment]
I agree with @swiftaction. Actually, you _do not need_ a settle-position order to short.  But you need a sell order with leverage to open a short position and then a settle-position order _to close it_.  See this [page](https://support.kraken.com/hc/en-us/articles/203250333-What-is-an-open-position-and-how-is-it-created-)

By going through the code it looks to me that blackbird will just call sendLongOrder to close the short position. 

If my understanding is ok(haven't touch C++ for a while) then the question is where is the best place to add this special short closing order? 

If I modified the sendLongOrder of Kraken.cpp it would result no long order can be made on Kraken. That does not sound good, isn't it?

**Comment by CCKRK** [comment]
@dixia why do you believe that you need a settle-position order to close your short? I simply added leverage=2  to my "options" string in kraken.cpp and I can open and close short orders just fine. I believe since in main.cpp sends "buy" as the type for closing the short leg it's totally fine. There's really no need to actually implement the leverage at this point.

**Comment by dixia** [comment]
I believe so because of Kraken documentation. 

But glad you shared this. The docs also described closing but a order with opposite direction. Not sure what is difference. But I suppose Kraken created it for a reason. 

BTW did you test it with a Kraken account? @CCKRK

**Comment by CCKRK** [comment]
I did unit tests on the Kraken sendShortOrder member (and the others) on a live Kraken account and everything worked, but I have not done any integration tests on the engine at large (my debug container is not currently working and to do that kind of testing I would have to do some pretty ghetto step through editing) 

I understand where you are coming from on settle-position and it was my first intuition as well, however, Kraken seems to do some strange things when you actually try to pass settle-position as the ordertype. 

The way their trading engine/match works, when you send your short leverage order you are committing some amount of your current (base currency) holdings to the trade and the margin requirements + other info seems to be calculated automatically. You can then set a limit order (with leverage) on the other side and your available margin balance remains unchanged (I think?) Regardless, I was able to submit a levered short for the full amount of the Kraken account and close it completely with a levered limit buy when the price of the leg1 currency went for and against my trades a few percent which were the cases I was worried about when not using settle-position or close-order.

**Pull request merged**
